[package]
name = "tusks-lib"
version = "1.2.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["string"] }
indexmap = "2.12.1"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.108", features = ["full"] }
